export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_SELECTED_PRODUCT = "SET_SELECTED_PRODUCT";
export const SET_DELETE_MODAL_OPEN = "SET_DELETE_MODAL_OPEN";
export const SET_MODAL_OPEN = "SET_MODAL_OPEN";
export const SET_IS_NEW_PRODUCT = "SET_IS_NEW_PRODUCT";
